---
- name: Configure Jenkins Agent Server
  hosts: all
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-21-jre
        state: present

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Create app directory
      file:
        path: /opt/app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Print confirmation
      debug:
        msg: "Server {{ inventory_hostname }} configured successfully by Ansible"
